### ISSUE TITLE
System switch "Use dark menu bar and Dock" doesn't work after using Panda

### ISSUE THREAD

**Issue by sermelipharo** [pablosproject/Panda-app#1]

**Comment by pablosproject** [comment]
Panda set the parameter ""AppleInterfaceStyle" to "Dark". The problem here is that the setting panel is not updating when panda switch mode. 

You should make Panda return to white mode and then you can use the system setting panel. I'm releasing a new version that correct this issue.

**Comment by sermelipharo** [comment]
If I return Panda to white mode — I still have some issues. Here is a video showing various combinations of Panda and system states: https://youtu.be/ih-9CoUXlpI 
if Panda=white — the dock and menubar icons remain to be light themed, same for spotlight.

**Comment by pablosproject** [comment]
You are right. I need to add a field in the menu that clear all settings that Panda adds to system preferences, and this will fix the problem. I'm working on this.

**Comment by TheBreznsoiza** [comment]
when we can see a fix for this? 

thanks

**Comment by pablosproject** [comment]
Fixed with the latest release.
